Fix failing spec - missing mock data
Dialog field test #dateTimeFieldChanged calls onUpdate with the correct full date FAILED
	TypeError: undefined is not an object (evaluating 'this.dialogField.options.show_past_dates') (line 9)
	setMinDate@dist/js/ui-components.js:9:120490
	$onInit@dist/js/ui-components.js:9:116953
	src/dialog-user/components/dialog-user/dialogField.spec.ts:189:35
	WorkFn@node_modules/angular-mocks/angular-mocks.js:3130:26
	src/dialog-user/components/dialog-user/dialogField.spec.ts:187:32
	inject@node_modules/angular-mocks/angular-mocks.js:3093:34
	src/dialog-user/components/dialog-user/dialogField.spec.ts:187:32

(cherry picked from commit d9c32f0ea89757f3da9b3d75bf64fcc60beced29)