Fix at-loader failures in specs
Fixes https://travis-ci.com/github/ManageIQ/ui-components/builds/182803973

    ERROR in [at-loader] ./node_modules/@types/lodash/common/common.d.ts:12:20
    TS2370: A rest parameter must be of an array type.

    ERROR in [at-loader] ./node_modules/@types/lodash/common/common.d.ts:255:22
    TS2304: Cannot find name 'unknown'.

    ERROR in [at-loader] ./node_modules/@types/lodash/common/function.d.ts:562:38
    TS2304: Cannot find name 'Parameters'.

(211 errors)

These seem to be caused by newer versions of lodash not conforming to the ancient @types/lodash schema.
Since @types/ repos are obsolete and removing it fixes the problem, doing that.