dialogField - fix gaprindashvili build problem
ERROR in ./src/dialog-user/components/dialog-user/dialogField.ts
(112,7): error TS2322: Type '0' is not assignable to type 'null'.

ERROR in ./src/dialog-user/components/dialog-user/dialogField.ts
[110, 70]: Missing semicolon
[113, 56]: Missing semicolon