dialogField - fix _.isObject vs typescript
typescript assumes that in `if (_.isObject(foo)) { ...`, `foo` will have the typescript `object` type

that causes

    ERROR in [at-loader] ./src/dialog-user/components/dialog-user/dialogField.ts:55:54
      TS2339: Property 'isValid' does not exist on type 'object'.

    ERROR in [at-loader] ./src/dialog-user/components/dialog-user/dialogField.ts:56:51
      TS2339: Property 'message' does not exist on type 'object'.

even though the type is set to `any`.

Fortunately `this.validation` can only be the validation object or null.